name: Backend CI/CD — Node.js -> Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '22'   # change if you use a different Node LTS

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps & run tests
        working-directory: ./backend
        run: |
          npm ci
          npm test

      - name: Build production package for Lambda
        working-directory: ./backend
        run: |
          # ensure production deps only for smaller zip
          npm ci --production
          # create a zip of the function contents (exclude local env / tests)
          ZIPFILE="../backend-function.zip"
          rm -f $ZIPFILE
          zip -r $ZIPFILE . -x ".git/*" "node_modules/**/*.md" "tests/*" ".env*" "*.log"

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
            --zip-file "fileb://./backend-function.zip"

      - name: Optional: run DB seed (if enabled)
        if: ${{ secrets.RUN_DB_SEED == 'true' }}
        working-directory: ./backend
        run: |
          # example: a script that uses AWS creds to seed DynamoDB
          npm run seed

      - name: Cleanup artifact
        run: rm -f ./backend-function.zip
